name = "chat-demo"
compatibility_date = "2024-01-01"

main = "src/chat.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

# Indicate that you want the ChatRoom class to be callable as a Durable Object.
[[migrations]]
tag = "v2"                                       # Should be unique for each entry
new_sqlite_classes = ["ChatRoom"]
